service: lambda-boilerplate
frameworkVersion: '3'

provider:
  name: aws
  useDotenv: true
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  endpointType: EDGE
  deploymentBucket:
    name: danimaxrestaurantlambda
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*

functions:
  api:
    handler: dist/index.orders_Handler
    environment:
      WAREHOUSE_QUEUE_URL: ${construct:warehouse.queueUrl}
    events:
      - http:
          path: v1/orders
          method: post

constructs:
  kitchen-delivery:
      type: queue
      fifo: true
      Properties:
        ContentBasedDeduplication: false
      worker:
          handler: dist/index.ordersHandler
  warehouse:
      type: queue
      fifo: true
      Properties:
          ContentBasedDeduplication: false
      worker:
          handler: dist/index.ordersHandler

plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-jest-plugin
  - serverless-lift

custom:
  jest:
    verbose: true
    collectCoverage: true 
  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: production
  ncc:
    concurrency: 3 # Quantity of files being compiled at the same time
    excludeDependencies: false # Exclude all the dependencies of package.json
    minify: true # @vercel/ncc option
    sourceMap: false # @vercel/ncc option
    sourceMapRegister: true # @vercel/ncc option

package:
  exclude:
    - node_modules/**
